/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.main.java.Unravel.Spring.Boot;
import org.springframework.boot.SpringApplication;

@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SpringApplication AppObject = new SpringApplication(App.class);
        AppObject.run(args);
    }
}
